apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api-deployment
  labels:
    app: orders-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
      - name: orders-api-container
        image: ashwanitaneja88/order_api_dimg:latest
        ports:
          - containerPort: 80