# sqlserver storage class and volume claim: sqlserver-volume.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: repd-us-central1-c
provisioner: kubernetes.io/gce-pd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: repd-us-central1-c